#!/bin/sh

DATABASE=jdf
USERNAME=jethro

# table, columns, dir, file
import(){
	COMMAND="COPY $1 ($2)\
		FROM STDIN WITH (FORMAT \"csv\", NULL 'NULL') ;"
	cat data/utf/$3/$4.txt | \
		./preformat $3 {} |\
		psql -c "$COMMAND" $DATABASE $USERNAME
		
}

echo Importuji...
for d in `ls -d data/utf/*/`;
	do
		echo $d;
		DIR=`basename $d`

		VERSION=`cat data/utf/$DIR/VerzeJDF.txt | cut -d \" -f 2`
		echo Verze $VERSION
		if [ $VERSION != "1.11" ]
		then
			continue
		fi

		echo Zastavky
		import zastavky "route,cislo,obec,cast_o,misto,blizko,stat,\
			p_kod1,p_kod2,p_kod3,p_kod4,p_kod5,p_kod6" $DIR Zastavky
		
		echo Pevny kod
		import pevnykod "route,cislo,znacka,rezerva" $DIR Pevnykod
		
		echo Dopravci
		import dopravci "route,ICO,DIC,jmeno,druh,jmeno_os,adresa,\
			tel_sidlo,tel_disp,tel_info,\
			fax,email,www,rozliseni" $DIR Dopravci

		echo Linky
		import linky "route,cislo,nazev,ICO,typ,prostredek,vyluka,\
			seskupeni,oznacnik,jednosmer,rezerva,\
			licence,licence_od,licence_do,jr_od,jr_do,rozl_dop,rozl_linky" $DIR Linky
		echo Spoje
		import spoje "route,linka,spoj,p_kod1,p_kod2,p_kod3,p_kod4,p_kod5,\
			p_kod6,p_kod7,p_kod8,p_kod9,p_kod10,skupina,rozl_linky" $DIR Spoje

		echo Zaslinky
		import zaslinky "route,linka,tarif_cis,tarif_pasmo,zastavka,\
			avg_doba,p_kod1,p_kod2,p_kod3,rozl_linky" $DIR Zaslinky

		echo Zasspoje
		import zasspoje "route,linka,spoj,tarif_cis,zastavka,kod_oznacniku,\
			stanoviste,p_kod1,p_kod2,p_kod3,km,\
			prijezd,odjezd,prij_min,odj_max,rozl_linky" $DIR Zasspoje

		if [ -e data/utf/$DIR/Udaje.txt ]
		then
			echo Udaje
			import udaje "route,linka,udaj,text,rozl_linky" $DIR Udaje
		fi
		

		echo Caskody
		import caskody "route,linka,spoj,cas_kod,cas_kod_ozn,cas_kod_typ,\
			datum_od,datum_do,poznamka,rozl_linky" $DIR Caskody
		
		if [ -e data/utf/$DIR/Altdop.txt ]
		then
			echo Altdop
			import altdop "route,linka,spoj,ICO,\
				p_kod1,p_kod2,p_kod3,p_kod4,p_kod5,p_kod6,\
				cas_kod_typ,rezerva,datum_od,datum_do,rozl_dop,rozl_linky" $DIR Altdop
		fi

		if [ -e data/utf/$DIR/Altlinky.txt ]
		then
			echo Altlinky
			import altlinky "route,linka,alt_linka,stat,rozl_linky" $DIR Altlinky
		fi

		if [ -e data/utf/$DIR/Mistenky.txt ]
		then
			echo Mistenky
			import mistenky "route,linka,spoj,text,rozl_linky" $DIR Mistenky
		fi

	done


