#!/bin/sh

DATABASE=jdf
USERNAME=jethro

echo Importuji zastavky...
for d in `ls -d data/utf/*/`;
	do
		echo $d;
		DIR=`basename $d`
		COMMAND="COPY zastavky \
			(route,cislo,obec,cast_o,misto,blizko,stat,\
			p_kod1,p_kod2,p_kod3,p_kod4,p_kod5,p_kod6)\
			FROM STDIN WITH (FORMAT \"csv\") ;"
		cat data/utf/$DIR/Zastavky.txt | \
			./preformat $DIR {} |\
			psql -c "$COMMAND" $DATABASE $USERNAME
	done



